spring:
  cloud:
    config:
      server:
        git:
          uri:{$vcap.services.git-repo.credentials.uri}
          username: {$vcap.services.git-repo.credentials.username}
          username: {$vcap.services.git-repo.credentials.password}
security:
  user:
    name: user
    password: pass          