spring:
  cloud:
    config:
      server:
        git:
          uri:${vcap.services.config-repo-service.credentials.uri}
          username: ${vcap.services.config-repo-service.credentials.username}
          password: ${vcap.services.config-repo-service.credentials.password}
security:
  user:
    name: user
    password: pass          